### ISSUE TITLE
Request:  Allow size dimensions on the umap plot

### ISSUE THREAD

**Issue by arnicas** [koaning/bulk#21]
Another potential for simple command line, or yaml: what should the dimensions of the umap plot display be?

**Comment by koaning** [comment]
Bokeh only allows selection on a 2d plane, so I think we're constrained by that. 

I've also tried doing selections in 3d and found them to be terribly unintuitive.

**Comment by arnicas** [comment]
I meant size in pixels for the plot layout itself in the html window.  I want it bigger :)

**Comment by koaning** [comment]
Ah like that! That should be easily configurable, sure.

**Comment by koaning** [comment]
One thing that's in the background: I haven't decided if I want to keep using the Bokeh layout or if I want to roll my own by integrating it with my a FastAPI server. I'll have a lot more control over the visual in the latter scenario, but it would also involve a lot more work and it might go beyond the appetite of my employer in the short term. 

I agree that this should be configurable, but I may want to delay the config system until I've decided if I'm using Bokeh or something custom.

**Comment by remydecoupes** [comment]
@arnicas : If you need to enlarge the UMAP fig, you could it manually by fixing the `plot_width` and `plot_height` in [code](https://github.com/koaning/bulk/blob/main/bulk/cli/text.py#L72)

**Comment by arnicas** [comment]
Sure - I had already hacked it a lot for personal use. I was just registering my issues as requests.

**Comment by koaning** [comment]
It's still something that's in the back of my mind by the way 🙂 but doing this may require a config system because there are many other things people may want to configure. Things like size of the dot in the chart, etc.

**Comment by koaning** [comment]
Closing this issue. The future of this project is Jupyter Widgets.
