### ISSUE TITLE
missing the demo .csv file

### ISSUE THREAD

**Issue by shauryr** [koaning/bulk#26]
Hi, love the tool!
I am not able to run the demo though. Can you help please?

**Comment by koaning** [comment]
You're supposed to run it on your own datasets.

But the next version will also have a download command that lets you download example datasets.

**Comment by shauryr** [comment]
yes I did run it on my own data. It expects the column 'text' be included. 
Also, is there a way to show more columns in the browser interface? For example showing ID of the text as column and download that as a .csv file. This feature would be great!

**Comment by koaning** [comment]
That sounds like something that I might want to add to a configuration file at some point. Will keep that in mind.

**Comment by koaning** [comment]
I just pushed a version that has a `download` command. Will think about some fun text examples to add as well.
