### ISSUE TITLE
Bulk Images Update

### ISSUE THREAD

**Issue by wjbmattingly** [koaning/bulk#29]
I have not posted here in a while, but I have been expanding the images version of bulk over the past month. It has quite a few features as well as the code to wrap bulk around docarray, umap, and hdbscan for processing images in multiple directories, embed them, flatten them, and isolate clusters and assign labels.

On the bokeh server side, it allows for you to hover over images as well as isolate different labels in a multiselect menu. (I am debugging a few things with multiselect now so that it communicates with the scatter plot and DataTable.

If you are interested, let me know and I can post a bit more.

P.S. I just saw your message on the PR. I am so sorry I missed your messages. I have been a bit busy with vacation/getting used to Croatia. I am back now and more than happy to help out with this, if you like. There is also a researcher at USHMM who has been working on his own version of this.

![image](https://user-images.githubusercontent.com/62964060/193046144-c8ec010c-653c-4b3a-9e39-10f2deb98628.png)

**Comment by koaning** [comment]
Just to check, have you seen the `image` feature on the main branch now? I'm still exploring ways to unit test it but it's already something that I've merged in. 

Preview: 
![CleanShot 2022-09-30 at 11 41 41](https://user-images.githubusercontent.com/1019791/193242399-07ee1baa-68ab-443c-9159-fc61c008646f.png)

**Comment by koaning** [comment]
I'm not 100% sure if this repo should have the hover feature, mainly because it can get _very_ distracting. 

Another thing that might be good to mention; it's possible that in the future, there will be an appetite to build a fully custom UI for this project. That would mean that we might move away from Bokeh. This is what the Dutch would call "future music", so while it is not something that I'm terribly concerned with right now ... it's something for the back of the mind.

**Comment by koaning** [comment]
I also wonder if we want to host a single image in each row. Mainly because it'll be much harder to get a big-picture overview without having to scroll. 

What this issue is making me wonder though ... is if I might want to implement a plugin system. One that would allow users to write an extension for the table on the right-hand side. I do see the "download" option as a potentially nice feature to some, but I'm a bit uneasy about implementing a huge config file where I need to worry about all the settings a user might want to pass.

**Comment by wjbmattingly** [comment]
> Just to check, have you seen the `image` feature on the main branch now? I'm still exploring ways to unit test it but it's already something that I've merged in.

Thanks for this! I had not checked out the new image feature. I will be sure to do so today or this weekend.

Thanks for the update

> I'm not 100% sure if this repo should have the hover feature, mainly because it can get very distracting.
I agree. I have it set to toggle on and off, so the user can easily just turn off the hover feature. 

> Another thing that might be good to mention; it's possible that in the future, there will be an appetite to build a fully custom UI for this project. That would mean that we might move away from Bokeh. This is what the Dutch would call "future music", so while it is not something that I'm terribly concerned with right now ... it's something for the back of the mind.

Thanks for letting me know about this. Right now, I am building this primarily to use at the Smithsonian and USHMM with a person at each institution. I would love to hear more about the custom UI as it progresses.


> I also wonder if we want to host a single image in each row. Mainly because it'll be much harder to get a big-picture overview without having to scroll.

This is a good point. I like how you have down it in a grid. I can see the advantages of both, depending on the use-case.

> What this issue is making me wonder though ... is if I might want to implement a plugin system. One that would allow users to write an extension for the table on the right-hand side. I do see the "download" option as a potentially nice feature to some, but I'm a bit uneasy about implementing a huge config file where I need to worry about all the settings a user might want to pass.

**Comment by wjbmattingly** [comment]
By the way, I am still cleaning up the code, but let me know if you want to take a look at the app I developed. I veered away from your code quite a bit this time out of necessity to incorporate all the components I needed. I have it in a private repo at the moment because the images belong to USHMM, but I can easily make another repo with other images and make that one public.

**Comment by koaning** [comment]
Let me know once the code is clean/tested. I'm a bit scrambled for time now that there's a newborn around 😅

**Comment by wjbmattingly** [comment]
We have cleaned and tested the code. Here is a link to the repo: https://github.com/wjbmattingly/bulk-image-clustering. I tried to make sure to give you proper credit. If you would like to be referenced any other way, please let me know. The README should explain how everything works, but if you have any questions, just let me know.

Congrats on being a new father! That is fantastic news! Absolutely no rush on this.

**Comment by koaning** [comment]
Bulk images has iterated so much that it's going to be tricky to merge it with this work. I revamped the backend a bit to handle `--download` functionality in https://github.com/koaning/bulk/pull/45.
