### ISSUE TITLE
Load json and jsonl files

### ISSUE THREAD

**Issue by rsbohn** [koaning/bulk#32]
Finding .csv files a bit limiting.

```python
def read_any(file:Path) -> DataTable:
    if file.name[-5:] == "jsonl":
        return pd.read_json(file, lines=True)
    if file.name[-4:] == "json":
        return pd.read_json(file)
    if file.name[-3:] == "csv":
        return pd.read_csv(file)
    raise ValueError(f"Can't read {file}.")
```

**Comment by koaning** [comment]
I wouldn't mind adding `.jsonl` but is `.json` really a format people use for something that is columnar?

**Comment by rsbohn** [comment]
I've been using `datasette` and `sqlite-utils` where the default format is .json. You can get .jsonl by adding '--nl'.

https://sqlite-utils.datasette.io/en/stable/cli.html#returning-json

**Comment by koaning** [comment]
I'm adding support for `jsonl` in https://github.com/koaning/bulk/pull/45. 

For now I'll consider json out of scope for this project. Partially because `.jsonl` feel superior, but also because it simplifies things.
