### ISSUE TITLE
bulk text not rendering

### ISSUE THREAD

**Issue by gabriead** [koaning/bulk#40]
Hi @koaning I was running bulk on text with my data (using the code snippet as in embed.py). It produces the dataframe  (ready.csv) but it does not open the bokeh UI after running python -m bulk text ready.csv. It doesn't run any local server on the terminal and also does not show any error.

**Comment by koaning** [comment]
How large is the .csv file? Big?

**Comment by koaning** [comment]
Also, any details on Python version/OS/etc?

**Comment by gabriead** [comment]
Good Morning @koaning, I cloned your repo again and now it works like a charme :-)
