### ISSUE TITLE
Help creating pipeline

### ISSUE THREAD

**Issue by phgoddard** [koaning/bulk#42]
Thanks for the great tool.  I'm just getting started and got stuck making the pipeline.  I've installed embetter.text and imported SentenceEncoder.
I've also installed sentence-transformers.
Running into error 'pip install embetter[sbert] though I'm able to create a model using:
model = SentenceTransformer('all-MiniLM-L6-v2') screen shot attached:

![2022-12-04_20-43-12](https://user-images.githubusercontent.com/70239535/205551943-da4d361a-3687-4771-95fc-49b349f57d71.png)

Can you help me - thanks.

**Comment by koaning** [comment]
I think this is a mistake on the `embetter` side. Could you try: 

```
python -m pip install "embetter[text]" 
```

It should also be fixed via: 

```
python -m pip install sentence-transformers
```

You will likely need to restart your Python env to get this to work though.

**Comment by koaning** [comment]
I did find the bad error message that mentions `sbert` instead of `text`. Will push a new version with a fix in a bit.

**Comment by phgoddard** [comment]
thank you - past the error now.
