### ISSUE TITLE
warn when column is missing

### ISSUE THREAD

**Issue by Ntarek** [koaning/bulk#50]
I am currently having an issue with the text not appearing when selecting a cluster of data in the web app. However, the rest of the data seems to appear in the plot. I have followed the video and written tutorials closely but keep getting the same problem with any CSV files used.

<img width="1128" alt="Screen Shot 2023-02-06 at 1 13 43 PM" src="https://user-images.githubusercontent.com/89796978/217058365-62c40dbd-a72f-4f1c-9841-bb50346f8685.png">

Also, when saving the data to a new CSV file from the app, the content text is displayed correctly. This leads me to believe that is primarily an issue with the text rendering not the input data.

<img width="946" alt="Screen Shot 2023-02-06 at 1 44 02 PM" src="https://user-images.githubusercontent.com/89796978/217057944-cf4ace16-b301-415e-a0bd-bfdaf77562fe.png">

I've tried with multiple browsers (Chrome, Safari, and Edge) as well as multiple devices (both MacOS and Windows) but I'm still getting the same error.

I would greatly appreciate your help. Thank you!

Python version: 3.9.13
Bokeh version: 2.4.3
Bulk version: 0.2.0

**Comment by koaning** [comment]
You need to add the text in the `text` column. Otherwise, it won't render. If this is the issue I should add an error to make users aware. 

If that does not help, could you try and older version and let me know if that fixes it?

**Comment by Ntarek** [comment]
It worked! I changed the name of the column to 'text' in the csv file and everything appeared correctly. Thank you so much!

**Comment by koaning** [comment]
reminder: add warning
