### ISSUE TITLE
Request: More efficent usage of browser space.

### ISSUE THREAD

**Issue by CGCooke** [koaning/bulk#57]
It would be great to fully use the floorspace available in the Browser window.

IE, The number of rows/columns of images, and the size of the graph responding to the available resolution.

**Comment by koaning** [comment]
This seems reasonable, but I'm not 100% sure if Bokeh has great support for this.

If you could pinpoint though, what's the main element that's too small now? The text field or the drawing area?

**Comment by manmax31** [comment]
In my case, my text is long, It will be great if we can scroll right or wrap text

**Comment by koaning** [comment]
Closing this issue. The future of this project is Jupyter Widgets.
