### ISSUE TITLE
Request: Save as HTML

### ISSUE THREAD

**Issue by LukasKriesch** [koaning/bulk#61]
Hi,

would be great if I could save the figure as .html file and send it to others. Is this possible?

Best

**Comment by koaning** [comment]
Not sure actually, does Bokeh have this feature?

**Comment by LukasKriesch** [comment]
Yes, it has.
from bokeh.io import save

save(your_figure, filename='bulk.html')

**Comment by koaning** [comment]
Closing this issue. The future of this project is Jupyter Widgets.
